version: "3.9"
services:
  app:
    build: .
    environment:
      - DB_DSN=${DB_DSN:-sqlite+aiosqlite:///./dev.db}
      - JWT_SECRET=${JWT_SECRET:-dev-secret}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: flags
    ports:
      - "5432:5432"
